[package]
name = "ble_to_postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
btleplug = { version = "0.10", features = ["tokio"] }
tokio-postgres = "0.7"
log = "0.4"
env_logger = "0.10"